apiVersion: apps/v1 #La versión de la API que vamos a usar; en este caso la v1.
kind: Deployment #La clase de recurso que estamos definiendo; en este caso un deployment.
metadata: #Información que nos permite identificar unívocamente el recurso.
  name: mariadb-deployment #Nombre del pod, replicaset y deployment
  labels: #Permiten etiquetar los recursos de Kubernetes con información del tipo clave/valor.
    app: symfony
    type: database
spec: #Definimos las características del recurso.
  replicas: 1 #Indicamos el número de Pods que siempre se deben estar ejecutando.
  selector: #Indicamos los Pods que va a controlar el ReplicaSet por medio de las etiquetas.
    matchLabels:
      app: symfony
      type: database
  template: #El recurso ReplicaSet contiene la definición de un Pod. 
    metadata:
      labels:
        app: symfony
        type: database
    spec: #Definimos las características del recurso.
      containers:
        - name: contenedor-mariadb #Nombre del contenedor.
          image: mariadb #La imagen desde la que se va a crear el contenedor
          ports: #Indicamos el puerto del contenedor y un nombre.
            - containerPort: 3306
              name: db-port
          env: #Variables de entorno
            - name: MYSQL_USER #Nombre de la variable del usuario normal de la bd.
              valueFrom: #Le indicamos el valor
                configMapKeyRef: #Le indicamos que busque en un configmap.
                  name: bd-datos #Indicamos que busque en este configmap.
                  key: bd_user #Le pedimos que recupere este valor.
            - name: MYSQL_DATABASE #Nombre de la variable del nombre de la bd.
              valueFrom:
                configMapKeyRef:
                  name: bd-datos
                  key: bd_dbname
            - name: MYSQL_PASSWORD #Nombre de la variable de la contraseña del usuario normal de la bd.
              valueFrom:
                secretKeyRef: #Le indicamos que busque en un secret.
                  name: bd-passwords
                  key: bd_password
            - name: MYSQL_ROOT_PASSWORD #Nombre de la variable de la contraseña del usuario root en la bd.
              valueFrom:
                secretKeyRef:
                  name: bd-passwords
                  key: bd_rootpassword
          volumeMounts: #Indicamos punto de montaje del volumen
            - name: mariadb-vol #Nombre del volumen
              mountPath: /var/lib/mysql #Ruta donde montamos el volumen.
      volumes: #Le indicamos que va a usar un volumen.
        - name: mariadb-vol #Nombre del volumen
          persistentVolumeClaim: #Indicamos que usara un volumen unico.
            claimName: mariadb-pvc #Buscara este volumen para usarlo.
