apiVersion: apps/v1 #La versión de la API que vamos a usar; en este caso la v1.
kind: Deployment #La clase de recurso que estamos definiendo; en este caso un deployment.
metadata: #Información que nos permite identificar unívocamente el recurso.
  name: symfony-deployment-final #Nombre del pod, replicaset y deployment
  labels: #Permiten etiquetar los recursos de Kubernetes con información del tipo clave/valor.
    app: symfony
    type: framework
spec: #Definimos las características del recurso.
  replicas: 1 #Indicamos el número de Pods que siempre se deben estar ejecutando.
  selector: #Indicamos los Pods que va a controlar el ReplicaSet por medio de las etiquetas.
    matchLabels:
      app: symfony
      type: framework
  template: #El recurso ReplicaSet contiene la definición de un Pod. 
    metadata:
      labels:
        app: symfony
        type: framework
    spec: #Definimos las características del recurso.
      containers:
        - name: contenedor-symfony #Nombre del contenedor.
          image: tupetanquero/pproyectosymfony5:v1 #La imagen desde la que se va a crear el contenedor
          ports: #Indicamos el puerto del contenedor y un nombre.
            - containerPort: 80
              name: http-port
            - containerPort: 443
              name: https-port
          env: #Variables de entorno
            - name: SYMFONY_DB_HOST #Nombre de la variable de la ip para conectar con la bd.
              value: mariadb-service
            - name: SYMFONY_DB_USER #Nombre de la variable del usuario normal de la bd.
              valueFrom:
                configMapKeyRef:
                  name: bd-datos
                  key: bd_user
            - name: SYMFONY_DB_PASSWORD #Nombre de la variable de la contraseña del usuario normal de la bd.
              valueFrom:
                secretKeyRef:
                  name: bd-passwords
                  key: bd_password
            - name: SYMFONY_DB_NAME #Nombre de la variable de la bd.
              valueFrom:
                configMapKeyRef:
                  name: bd-datos
                  key: bd_dbname
